name: Validate Prompts

on:
  push:
    branches: [ main, master, develop, feature/* ]
  pull_request:
    branches: [ main, master, develop, feature/* ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./catalog

      - name: Sync latest schema from contracts
        run: npm run sync:schema
        working-directory: ./catalog

      - name: Validate prompts
        run: npm run validate
        working-directory: ./catalog 